version: '3'
services:

  wordpress:
    image: ${WP_IMAGE}
    working_dir: ${WP_ROOT_DIR}
    ports:
      - "${WP_PUBLISHED_PORT}:80"
      - "${WP_PUBLISHED_PORT_HTTPS}:443"
    restart: on-failure
    depends_on:
      - database
    volumes:
      - ./:${WP_PROJECT_DIR}
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}

  wordpress_php5.6:
    image: tfirdaus/wp-docklines:php5.6-fpm-alpine
    working_dir: ${WP_PROJECT_DIR}
    depends_on:
      - database
    volumes:
      - ./:${WP_PROJECT_DIR}
      - wp_core:/tmp/wordpress/
      - wp_tests_dir:/tmp/wordpress-tests-lib

  wordpress_php7.0:
    image: tfirdaus/wp-docklines:php7.0-fpm-alpine
    working_dir: ${WP_PROJECT_DIR}
    depends_on:
      - database
    volumes:
      - ./:${WP_PROJECT_DIR}
      - wp_core:/tmp/wordpress/
      - wp_tests_dir:/tmp/wordpress-tests-lib

  wordpress_php7.1:
    image: tfirdaus/wp-docklines:php7.1-fpm-alpine
    working_dir: ${WP_PROJECT_DIR}
    depends_on:
      - database
    volumes:
      - ./:${WP_PROJECT_DIR}
      - wp_core:/tmp/wordpress/
      - wp_tests_dir:/tmp/wordpress-tests-lib

  wordpress_php7.2:
    image: tfirdaus/wp-docklines:php7.2-fpm-alpine
    working_dir: ${WP_PROJECT_DIR}
    depends_on:
      - database
    volumes:
      - ./:${WP_PROJECT_DIR}
      - wp_core:/tmp/wordpress/
      - wp_tests_dir:/tmp/wordpress-tests-lib

  node:
    image: ${NODE_IMAGE}
    working_dir: ${WP_PROJECT_DIR}
    volumes:
      - ./:${WP_PROJECT_DIR}

  database:
    image: ${DB_IMAGE}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${DB_PUBLISHED_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

# Cache the database.
volumes:
  mysql:
  wp_core:
  wp_tests_dir:
